### ISSUE TITLE
No fragments found! With custom genome and gene annotation.

### ISSUE THREAD

**Issue by derpylz** [GreenleafLab/ArchR#1014]
Hello ArchR team!
First of all, thanks for the great package, I've successfully been able to use it for some of my data. However now, I'm trying to analyze data that's not from a species with an included genome annotation. I've run into the following problem:

**Attach your log file**
[ArchR-createArrows-30e571beb144-Date-2021-09-02_Time-12-32-10.log](https://github.com/GreenleafLab/ArchR/files/7098912/ArchR-createArrows-30e571beb144-Date-2021-09-02_Time-12-32-10.log)

**Describe the bug**
Using a custom gene and genome annotation (based on the UCSC calJac4 genome), the createArrowFiles() function fails in the "Reading TabixFile" step with the following error message:

```
2021-09-02 12:32:11 : (sa165_Marmoset_Ovary_3w_F_cj4 : 1 of 1) Tabix Bed To Temporary File, 0.001 mins elapsed.
2021-09-02 12:32:36 : (sa165_Marmoset_Ovary_3w_F_cj4 : 1 of 1) Reading TabixFile 52 Percent, 0.432 mins elapsed.

************************************************************
2021-09-02 12:33:19 : ERROR Found in .tabixToTmp for (sa165_Marmoset_Ovary_3w_F_cj4 : 1 of 1) 
LogFile = ArchRLogs/ArchR-createArrows-30e571beb144-Date-2021-09-02_Time-12-32-10.log

<simpleError: No fragments found!
>

************************************************************

2021-09-02 12:33:19 : createArrowFiles has encountered an error, checking if any ArrowFiles completed..
ArchR logging successful to : ArchRLogs/ArchR-createArrows-30e571beb144-Date-2021-09-02_Time-12-32-10.log
```

My fragments file looks like this:

```
chr1    2076    2244    CTTGAAGCATTCCCGT-1      1
chr1    3352    3519    GGTAGGATCCCTACGT-1      1
chr1    3440    3522    ACTAACGAGAGAGGTA-1      1
chr1    6790    6986    GGTGCTGCACTGTTAG-1      1
chr1    10774   10933   CCCACATGTTCTGAGT-1      1
chr1    10844   10921   GGGTTATCATAGCCAT-1      1
chr1    10846   11066   AACAGTCTCGCAAACT-1      1
chr1    13087   13196   AATACGCTCCTCTCTT-1      1
chr1    13206   13758   TAGCGGCAGAGTGGAA-1      1
chr1    13237   13459   GCCAGACGTTTCCACC-1      1
chr1    13237   13743   CGAGTTATCTTACTCA-1      1
chr1    13618   13863   CTTCTAACATGGTATC-1      1
chr1    14204   14351   CATTGGACATCAGAAA-1      1
chr1    15934   16034   AACCTTTGTCAGTGTT-1      1
chr1    16264   16608   AATGTCGAGTAGGAAG-1      1
```

I've seen that this error came up here several times already, but the solutions given so far have not solved my problem.

* I've tried with ArchR 1.0.1 and 1.0.2.
* I've checked that the fragment file only has "normal" seqnames (chr1-22, chrX, chrY, chrM), and so do the fasta and gtf files that I used to create the genome and gene annotations for ArchR.
* I've run the fragment files through reformatFragmentFiles()

By now, I don't know what more to try, I'd greatly appreciate some hints. Let me know, if you need any further information.

**Session Info**
I've attached the log file, but here's the session info anyways:

```
R version 3.6.3 (2020-02-29)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 18.04.5 LTS

Matrix products: default
BLAS:   /usr/lib/x86_64-linux-gnu/openblas/libblas.so.3
LAPACK: /usr/lib/x86_64-linux-gnu/libopenblasp-r0.2.20.so

locale:
 [1] LC_CTYPE=C.UTF-8       LC_NUMERIC=C           LC_TIME=C.UTF-8       
 [4] LC_COLLATE=C.UTF-8     LC_MONETARY=C.UTF-8    LC_MESSAGES=C.UTF-8   
 [7] LC_PAPER=C.UTF-8       LC_NAME=C              LC_ADDRESS=C          
[10] LC_TELEPHONE=C         LC_MEASUREMENT=C.UTF-8 LC_IDENTIFICATION=C   

attached base packages:
[1] parallel  stats4    stats     graphics  grDevices utils     datasets 
[8] methods   base     

other attached packages:
 [1] Rsamtools_2.2.3             BSgenome.calJac4.ncbi_1.0  
 [3] BSgenome_1.54.0             rtracklayer_1.46.0         
 [5] Biostrings_2.54.0           XVector_0.26.0             
 [7] ArchR_1.0.2                 magrittr_2.0.1             
 [9] rhdf5_2.30.1                Matrix_1.3-2               
[11] data.table_1.14.0           SummarizedExperiment_1.16.1
[13] DelayedArray_0.12.3         BiocParallel_1.20.1        
[15] matrixStats_0.60.1          Biobase_2.46.0             
[17] GenomicRanges_1.38.0        GenomeInfoDb_1.22.1        
[19] IRanges_2.20.2              S4Vectors_0.24.4           
[21] BiocGenerics_0.32.0         ggplot2_3.3.5              

loaded via a namespace (and not attached):
 [1] tidyselect_1.1.1         purrr_0.3.4              lattice_0.20-44         
 [4] colorspace_2.0-2         vctrs_0.3.8              generics_0.1.0          
 [7] utf8_1.2.2               XML_3.99-0.3             rlang_0.4.11            
[10] pillar_1.6.2             glue_1.4.2               withr_2.4.2             
[13] DBI_1.1.1                GenomeInfoDbData_1.2.2   lifecycle_1.0.0         
[16] stringr_1.4.0            zlibbioc_1.32.0          munsell_0.5.0           
[19] gtable_0.3.0             Cairo_1.5-12.2           fansi_0.5.0             
[22] Rcpp_1.0.7               scales_1.1.1             stringi_1.7.4           
[25] dplyr_1.0.7              grid_3.6.3               bitops_1.0-7            
[28] tools_3.6.3              RCurl_1.98-1.4           tibble_3.1.4            
[31] crayon_1.4.1             pkgconfig_2.0.3          ellipsis_0.3.2          
[34] assertthat_0.2.1         Rhdf5lib_1.8.0           R6_2.5.1                
[37] GenomicAlignments_1.22.1 compiler_3.6.3
```

**Comment by rcorces** [comment]
Sorry you are having trouble. Can you provide all of the code that you used to create your custom genome annotation and arrow files?

**Comment by rcorces** [comment]
Actually, there is a bug in `1.0.2` that has been patched but the patch hasnt been merged yet. So at least in `1.0.2` you wont be able to make arrows. Can you try installing this branch, restarting your R session, and reloading ArchR and seeing if that fixes the problem?

```
devtools::install_github("GreenleafLab/ArchR", ref="dev_210701_createArrow", repos = BiocManager::repositories())
```

**Comment by Jianye-Chang** [comment]
> Actually, there is a bug in `1.0.2` that has been patched but the patch hasnt been merged yet. So at least in `1.0.2` you wont be able to make arrows. Can you try installing this branch, restarting your R session, and reloading ArchR and seeing if that fixes the problem?
> 
> ```
> devtools::install_github("GreenleafLab/ArchR", ref="dev_210701_createArrow", repos = BiocManager::repositories())
> ```

Thx!

**Comment by Jianye-Chang** [comment]
> Intalling the branch dev_210701_createArrow as per your suggestion solved this problem! Thanks a lot!
> 
> Now I get until Adding TileMatrix and get an error. I assume this error is caused by my custom annotation, possibly because the UCSC assembly is 0 indexed, I'll have to look into this.
> 
> ```
> 2021-09-02 14:35:15 : (sa165_Marmoset_Ovary_3w_F_cj4 : 1 of 1) Adding TileMatrix!, 3.211 mins elapsed.
> [1] "Bad1 (Start not greater than 0): "
> IRanges object with 0 ranges and 1 metadata column:
>        start       end     width |    RG
>    <integer> <integer> <integer> | <Rle>
> [1] "Bad2 (End greater than chromsome length): "
> IRanges object with 1 range and 1 metadata column:
>           start       end     width |
>       <integer> <integer> <integer> |
>   [1] 124486667 124486764        98 |
>                                                     RG
>                                                  <Rle>
>   [1] sa165_Marmoset_Ovary_3w_F_cj4#CCTGGGATCTGAGTCA-1
> 
> ************************************************************
> 2021-09-02 14:35:55 : ERROR Found in .addTileMat for sa165_Marmoset_Ovary_3w_F_cj4 
> LogFile = ArchRLogs/ArchR-createArrows-4675c8384f-Date-2021-09-02_Time-14-32-02.log
> 
> <simpleError in validObject(r): invalid class “dgTMatrix” object: lengths of slots i and j must match>
> 
> ************************************************************
> 
> 
> ************************************************************
> 2021-09-02 14:35:55 : ERROR Found in .addTileMat for (sa165_Marmoset_Ovary_3w_F_cj4 : 1 of 1) 
> LogFile = ArchRLogs/ArchR-createArrows-4675c8384f-Date-2021-09-02_Time-14-32-02.log
> 
> <simpleError in .logError(e, fn = ".addTileMat", info = sampleName, errorList = errorList,     logFile = logFile): Exiting See Error Above>
> 
> ************************************************************
> 
> 2021-09-02 14:35:55 : createArrowFiles has encountered an error, checking if any ArrowFiles completed..
> ```

Hi.Now I also get until Adding TileMatrix and get an error.Have you solved the problem yet?  Can you give me some advice  ?

**Comment by rcorces** [comment]
this is almost certainly a problem with your reference genome. there is not much help I can provide. make sure that the genome used for alignment and the genome used in ArchR are identical.

**Comment by derpylz** [comment]
Yes, as I expected it was an off-by-one error due to my genome assembly being 0-based. So fragments mapped to the last position of a sequence would look like they map to one base outside, and that's what causes this error. So if you have the same issue, you can either subtract 1 from the positions of your fragments file, or, probably better, make sure that the genome that you use for alignment and the one you use for ArchR are both 1-based (or both 0-based).

I think we can close this issue now, since the original error was solved (by using the branch dev_210701_createArrow).

**Comment by dagarfield** [comment]
> Yes, as I expected it was an off-by-one error due to my genome assembly being 0-based. So fragments mapped to the last position of a sequence would look like they map to one base outside, and that's what causes this error. So if you have the same issue, you can either subtract 1 from the positions of your fragments file, or, probably better, make sure that the genome that you use for alignment and the one you use for ArchR are both 1-based (or both 0-based).
> 
> I think we can close this issue now, since the original error was solved (by using the branch dev_210701_createArrow).

@derpylz , how did you diagnose this issue? I'm getting this same error (`invalid class “dgTMatrix” object: lengths of slots i and j must match`), but I can't see any difference in the lengths in my custom BSGenome and the chromosome/scaffold lengths given by the header of the 10x BAM file. 

I don't think I had this error with previous ArchR versions....

**Comment by ProphetDarkland** [comment]
> Actually, there is a bug in `1.0.2` that has been patched but the patch hasnt been merged yet. So at least in `1.0.2` you wont be able to make arrows. Can you try installing this branch, restarting your R session, and reloading ArchR and seeing if that fixes the problem?
> 
> ```
> devtools::install_github("GreenleafLab/ArchR", ref="dev_210701_createArrow", repos = BiocManager::repositories())
> ```

Hi, @rcorces I've also had this error:
```
ERROR Found in .tabixToTmp for (E19B_Lane3 : 166 of 181) 
<simpleError: No fragments found!
```
and I have tried ArchR 1.0.1 and ArchR 1.0.2, reformatFragmentFiles() to refine my fragments files and the installation code above, but the error still exists.
and when I use `devtools::install_github("GreenleafLab/ArchR", ref="dev_210701_createArrow", repos = BiocManager::repositories())` to install, it shows 
```
Error: Failed to install 'unknown package' from GitHub:
  HTTP error 404.
  No commit found for the ref dev_210701_createArrow
```
so maybe the dev_210701_createArrow is not exist and how can I solve this problem now? 
It also shows that some of my fragments file can create the arrow files and some can not...
