### ISSUE TITLE
Unable to create Arrow Files (including from tutorial data)

### ISSUE THREAD

**Issue by ew367** [GreenleafLab/ArchR#1435]
I have updated Ar:chR using:
`devtools::install_github("GreenleafLab/ArchR", ref="master", repos = BiocManager::repositories())`

**Attach your log file**
I have attached the log file for when I try to create arrow files using the tutorial data
[ArchR-createArrows-88a793f96bb-Date-2022-05-18_Time-13-34-37.log](https://github.com/GreenleafLab/ArchR/files/8716325/ArchR-createArrows-88a793f96bb-Date-2022-05-18_Time-13-34-37.log)

**Describe the bug**
When I try and create the arrowfiles using the tutorial data (or my own) in R.4. I get various error messages. I have tried calling `library(parallel)` at the beginning of the script, and various parameters for `addArchRThreads()`. Strangely, if I try running the `createArrowFiles()` repeatedly (without first removing the exisitng tutorial files), I am occasionally able to successfully make 2/3 of the arrowFiles.

I am seemingly able to create arrowFiles using R3.6, but am then unable to continue with any analysis as I am unable to install the Seurat package for this version of R.

**To Reproduce**
```
library(ArchR)
library(stringr)
library(parallel)

set.seed(1)
addArchRThreads(threads = 14) 
addArchRGenome("hg38")

inputFiles <- getTutorialData("Hematopoiesis")

ArrowFiles <- createArrowFiles(
  inputFiles = inputFiles,
  sampleNames = names(inputFiles),
  filterTSS = 4, #Dont set this too high because you can always increase later
  filterFrags = 1000, 
  addTileMat = TRUE,
  addGeneScoreMat = TRUE
)
```

**Expected behavior**
I expected arrowFiles to be created.

**Screenshots**
![image](https://user-images.githubusercontent.com/44901334/169043077-c573222f-01ea-4a40-9519-aa8a0a08e210.png)

**Session Info**
If you do not have a log file because the function that caused the error does not produce one, please paste the output of "sessionInfo()" here.

**Additional context**

**Comment by rcorces** [comment]
Thanks for using ArchR. Before answering the issue, I just want to point you to Item number 4 above - please avoid screenshotting text - it is not searchable so any users having a similar error would not be able to find this issue.

This looks like a permissions issue to me. You can try using `chmod` to force permissions on this directory or `umask` as suggested here - https://github.com/GreenleafLab/ArchR/issues/1183#issuecomment-980781270

This is almost certainly an environment-specific problem which is challenging to troubleshoot on my end so you will have to do some exploring.

**Comment by ew367** [comment]
Thanks for getting back to me so quickly. I am able to get 2 out of the 3 arrow files created for the tutorial data by doing the following:

immediately before calling `createArrowFiles()` (in this specific order)
```
library(parallel)
library(magick)
addArchRThreads(threads = 1) 
```

Only running ArchR in one R session! I had been running it in mutiple sessions (on different datasets) while I was troubleshooting which was also causing problems.

However the PBMC file is still failing at the very end of the process:

```
2022-05-18 15:06:05 : Batch Execution w/ safelapply!, 0 mins elapsed.
2022-05-18 15:06:05 : (scATAC_BMMC_R1 : 1 of 3) Arrow Exists! Marking as completed since force = FALSE!, 0 mins elapsed.
2022-05-18 15:06:05 : (scATAC_CD34_BMMC_R1 : 2 of 3) Arrow Exists! Marking as completed since force = FALSE!, 0.001 mins elapsed.
2022-05-18 15:06:05 : (scATAC_PBMC_R1 : 3 of 3) Reading In Fragments from inputFiles (readMethod = tabix), 0.001 mins elapsed.
2022-05-18 15:06:05 : (scATAC_PBMC_R1 : 3 of 3) Tabix Bed To Temporary File, 0.001 mins elapsed.
2022-05-18 15:06:33 : (scATAC_PBMC_R1 : 3 of 3) Reading TabixFile 42 Percent, 0.467 mins elapsed.
2022-05-18 15:06:56 : (scATAC_PBMC_R1 : 3 of 3) Reading TabixFile 83 Percent, 0.865 mins elapsed.
2022-05-18 15:07:04 : (scATAC_PBMC_R1 : 3 of 3) Successful creation of Temporary File, 0.991 mins elapsed.
2022-05-18 15:07:04 : (scATAC_PBMC_R1 : 3 of 3) Creating ArrowFile From Temporary File, 0.991 mins elapsed.
2022-05-18 15:07:32 : (scATAC_PBMC_R1 : 3 of 3) Successful creation of Arrow File, 1.452 mins elapsed.
2022-05-18 15:08:36 : createArrowFiles has encountered an error, checking if any ArrowFiles completed..
ArchR logging successful to : ArchRLogs/ArchR-createArrows-88a5cbb46b6-Date-2022-05-18_Time-15-06-04.log
Warning messages:
1: In sprintf("%s Reading TabixFile %s Percent", prefix, round(100 *  :
  one argument not used by format '%s Reading TabixFile %s Percent'
2: In sprintf("%s Reading TabixFile %s Percent", prefix, round(100 *  :
  one argument not used by format '%s Reading TabixFile %s Percent'
>
```
I've tried specificying   `cleanTmp = FALSE,  nChunk = 1`  as suggested here: https://github.com/GreenleafLab/ArchR/issues/1275 but it's not solved the issue

**Comment by ew367** [comment]
Hi, I've tried deleting and redownloading the tutorial data as you suggest, but I'm still having the same problem. When I look in the QC directory I can see a folder called "scATAC_PBMC_R1" but it only contains the fragment distribution pdf (there is no tss plot or rds file). I have two other 10x scATAC datasets, one of them has successfully created 21/21 arrowFiles/QC metrics etc and I am able to continue to downstream analyses., The other dataset (~21 samples again) is also producing the `createArrowFiles has encountered an error, checking if any ArrowFiles completed.` error and only creating the fragment distribution plot when it tries to process sample 3/21 (the first two samples process as expected).

**Comment by rcorces** [comment]
Can you update ArchR to the current development release `release_1.0.2` and try again?

```
devtools::install_github("GreenleafLab/ArchR", ref="release_1.0.2", repos = BiocManager::repositories())
detach("package:ArchR", unload=TRUE)
library(ArchR)
```

**Comment by rcorces** [comment]
Please always upload your log file and paste the text of the error from your console. Otherwise I cannot provide any help.

**Comment by rcorces** [comment]
You must not be following the tutorial code. You are using the `hg38` reference genome in this logfile. The tutorial is in `hg19`.

You logfile says:
```
2022-05-23 10:40:18 : Detected 2 or less cells pass filter (Non-Zero median TSS = 1.92, median Frags = 3313.5) in file!
       Check inputs such as 'filterFrags' or 'filterTSS' to keep cells! Exiting!
```
This is almost certainly because you are using the wrong reference genome.

**Comment by sunjiahe-hub** [comment]
![image](https://user-images.githubusercontent.com/69581197/170621164-3809b1bb-d261-426a-af6d-91aa9c0571d4.png)

Hello, I got the above error when I created ArrowFiles for BAM files, I tried to change the version, but still can't solve it, I hope to get your help, thank you

**Comment by sunjiahe-hub** [comment]
Here is the log file, thank you for your help!
[Uploading ArchR-createArrows-792d7e2b80ef-Date-2022-05-27_Time-03-24-36.log…]()

**Comment by rcorces** [comment]
@sunjiahe-hub - unless you are encountering exactly the same problem. please start a new post. However, I think your issue has already been solved. see https://github.com/GreenleafLab/ArchR/discussions/1044#discussioncomment-1654733

I'm closing this as I believe the original issue has been addressed.

**Comment by sunjiahe-hub** [comment]
thanks for your help！

**Comment by ew367** [comment]
Thanks @rcorces you are correct that I was using the wrong genome build for the tutorial data, thanks. (As an aside it might be helpful if this was flagged as a potential cause for being unable to create arrow files in the log files in future releases?).

I am still having a very similar issue with my own dataset however, which definitely uses hg38 for both cellranger and ArchR (cellranger code: `--reference=../refdata-cellranger-arc-GRCh38-2020-A-2.0.0 `). Could this be caused by an issue with the data quaility itself? I've attached the most recent log file for my data. I've been excluding samples that failed to create arrow files from my inputFiles object so this only shows the error for the last failed sample in the dataset, but they are similar errors along the lines of `2022-05-23 12:47:34 : Detected 2 or less cells pass filter (Non-Zero median TSS = 1.25, median Frags = 1271.5) in file!
       Check inputs such as 'filterFrags' or 'filterTSS' to keep cells! Exiting!`

Thanks for all your help so far, it is much appreciated!

[ArchR-createArrows-5fb25026a1c0-Date-2022-05-23_Time-19-06-48.log](https://github.com/GreenleafLab/ArchR/files/8787261/ArchR-createArrows-5fb25026a1c0-Date-2022-05-23_Time-19-06-48.log)

**Comment by rcorces** [comment]
@ew367 - I've updated the error message to include a suggestion to check that you are using the correct reference genome:
https://github.com/GreenleafLab/ArchR/commit/17dbf94f247d8b084493a49fac97664ccd3832b4

As to your problem, it is exactly what the error message says. You dont have cells that pass your cutoffs. If you look at the log, you will see this:
```
2022-05-23 19:08:19 : (10300_16849 : 17 of 18) BarcodeFrequencyTable, Class = data.frame
(10300_16849 : 17 of 18) BarcodeFrequencyTable: nRows = 82124, nCols = 2
            values.V1  V1
1: TACTCGCGTATGTTCG-1 962
2: AATGGCTTCCAGTACA-1 804
3: TTCAACTTCCGTTTCG-1 779
4: AAGGTTCCAGAATGCG-1 766
5: TAGCGGCAGACCAATA-1 744
6: TCTAGTTCAGGGTACA-1 720
```

Which shows that the cell with the most frags has 962 which is below `minFrags`.

**Comment by ew367** [comment]
Thanks @rcorces. After setting `filterTSS = 0 and minFrags = 0` the arrow files are now being created without errors
