### ISSUE TITLE
addImputeWeights with useHdf5=FALSE crashes

### ISSUE THREAD

**Issue by bnprks** [GreenleafLab/ArchR#532]
Description pretty much says it all -- reading the code in Imputation.R it appears that the function was not tested with useHdf5=FALSE
```
> proj <- addImputeWeights(proj, useHdf5=FALSE)
ArchR logging to : ArchRLogs/ArchR-addImputeWeights-3ad7a482fe979-Date-2021-02-11_Time-13-14-50.log
If there is an issue, please report to github with logFile!
2021-02-11 13:14:50 : Computing Impute Weights Using Magic (Cell 2018), 0 mins elapsed.
Error in file.remove(weightFiles) : object 'weightFiles' not found
```

**Comment by jgranja24** [comment]
I will take a look shortly. Its initial creation was with HDF5 = FALSE. There really isnt a reason i can imagine you would want this to be TRUE? This is a lot of memory usage that isnt really useful.

**Comment by jgranja24** [comment]
This is fixed --

```
devtools::install_github("GreenleafLab/ArchR", ref="release_1.0.2", repos = BiocManager::repositories())

library(ArchR)

proj <- getTestProject()

proj <- addImputeWeights(proj, useHdf5=FALSE)
# ArchR logging to : ArchRLogs/ArchR-addImputeWeights-111aa5509c08e-Date-2021-02-21_Time-21-24-47.log
# If there is an issue, please report to github with logFile!
# 2021-02-21 21:24:47 : Computing Impute Weights Using Magic (Cell 2018), 0 mins elapsed.

#            ___      .______        ______  __    __  .______      
#           /   \     |   _  \      /      ||  |  |  | |   _  \     
#          /  ^  \    |  |_)  |    |  ,----'|  |__|  | |  |_)  |    
#         /  /_\  \   |      /     |  |     |   __   | |      /     
#        /  _____  \  |  |\  \\___ |  `----.|  |  |  | |  |\  \\___.
#       /__/     \__\ | _| `._____| \______||__|  |__| | _| `._____|
    
# class: ArchRProject 
# outputDirectory: /Users/jeffreygranja/Desktop/PBMCSmall 
# samples(1): PBMCSmall
# sampleColData names(1): ArrowFiles
# cellColData names(18): Sample TSSEnrichment ... ReadsInPeaks FRIP
# numberOfCells(1): 2217
# medianTSS(1): 12.277
# medianFrags(1): 593

a <- proj@imputeWeights[[1]][[1]][[1]]

a[1:5, 1:5]
# > a[1:5, 1:5]
# 5 x 5 sparse Matrix of class "dgCMatrix"
#                              PBMCSmall#TATCTGTAGACAGCTG-1
# PBMCSmall#TATCTGTAGACAGCTG-1                 0.0126449498
# PBMCSmall#ATGGATCCAGGCAAGT-1                 0.0010368782
# PBMCSmall#CACATGAAGGCCTAAG-1                 0.0021986225
# PBMCSmall#CAAAGCTGTCTGATTG-1                 0.0008419275
# PBMCSmall#CTCATGCAGCAGTAGC-1                 0.0043500218
#                              PBMCSmall#ATGGATCCAGGCAAGT-1
# PBMCSmall#TATCTGTAGACAGCTG-1                 8.814603e-04
# PBMCSmall#ATGGATCCAGGCAAGT-1                 1.137344e-02
# PBMCSmall#CACATGAAGGCCTAAG-1                 3.277390e-05
# PBMCSmall#CAAAGCTGTCTGATTG-1                 4.744563e-08
# PBMCSmall#CTCATGCAGCAGTAGC-1                 8.589326e-05
#                              PBMCSmall#CACATGAAGGCCTAAG-1
# PBMCSmall#TATCTGTAGACAGCTG-1                 3.507735e-03
# PBMCSmall#ATGGATCCAGGCAAGT-1                 6.150765e-05
# PBMCSmall#CACATGAAGGCCTAAG-1                 7.943215e-03
# PBMCSmall#CAAAGCTGTCTGATTG-1                 5.721594e-03
# PBMCSmall#CTCATGCAGCAGTAGC-1                 6.305320e-03
#                              PBMCSmall#CAAAGCTGTCTGATTG-1
# PBMCSmall#TATCTGTAGACAGCTG-1                 1.701048e-03
# PBMCSmall#ATGGATCCAGGCAAGT-1                 1.127621e-07
# PBMCSmall#CACATGAAGGCCTAAG-1                 7.245741e-03
# PBMCSmall#CAAAGCTGTCTGATTG-1                 7.542966e-03
# PBMCSmall#CTCATGCAGCAGTAGC-1                 5.597494e-03
#                              PBMCSmall#CTCATGCAGCAGTAGC-1
# PBMCSmall#TATCTGTAGACAGCTG-1                 3.583441e-03
# PBMCSmall#ATGGATCCAGGCAAGT-1                 8.323248e-05
# PBMCSmall#CACATGAAGGCCTAAG-1                 3.255666e-03
# PBMCSmall#CAAAGCTGTCTGATTG-1                 2.282236e-03
# PBMCSmall#CTCATGCAGCAGTAGC-1                 6.728848e-03

```

**Comment by grimmem1** [comment]
I have the same issue and would like to install 1.0.2 but it seems no longer available. Is there an alternative resolution?

```
> devtools::install_github("GreenleafLab/ArchR", ref="release_1.0.2", repos = BiocManager::repositories())
Registered S3 method overwritten by 'cli':
  method     from         
  print.boxx spatstat.geom
Downloading GitHub repo GreenleafLab/ArchR@release_1.0.2
Error in utils::download.file(url, path, method = method, quiet = quiet,  : 
  download from 'https://api.github.com/repos/GreenleafLab/ArchR/tarball/release_1.0.2' failed
```

**Comment by grimmem1** [comment]
Solved for me: https://support.rstudio.com/hc/en-us/articles/206827897-Secure-Package-Downloads-for-R

**Comment by mzhibo** [comment]
I have the same issue and the method above did not solve it.

**Comment by mzhibo** [comment]
I ended up downloading the tarball and installed it from local tarballs. posting here in case others have the same issue.
```
wget https://api.github.com/repos/GreenleafLab/ArchR/tarball/release_1.0.2
install.packages("/mnt/c/Users/mzhib/Downloads/GreenleafLab-ArchR-v1.0.1-54-g12846a5.tar.gz", repos = NULL, type = "source")
```
