### ISSUE TITLE
Save of subsetted ArchR project fails at the metadata copy point

### ISSUE THREAD

**Issue by dagarfield** [GreenleafLab/ArchR#663]
The log file is attached, but does not seem very helpful in this case. 
[ArchR-saveArchRProject-1cf81f352c44-Date-2021-03-27_Time-18-57-51.log](https://github.com/GreenleafLab/ArchR/files/6219351/ArchR-saveArchRProject-1cf81f352c44-Date-2021-03-27_Time-18-57-51.log)

**Describe the bug**
I ran into an issue in getMarkerFeatures that I attempted to solve by first saving a subsetted ArchR project using dropCells = TRUE (https://github.com/GreenleafLab/ArchR/issues/483). However, I am running into the following error:

`projSpurp_doubletRemoved_filtered2<-saveArchRProject(ArchRProj = projSpurp_doubletRemoved_filtered, outputDirectory = "earlyCells_doubletRemoved_filtered2", load = TRUE, dropCells = TRUE,threads = 1)`

>Copying ArchRProject to new outputDirectory : /fast/work/projects/garfield-wrap-up/projects/13_alt_urchinATAC_processing/evaluating_early_stages/ArchR/earlyCells_doubletRemoved_filtered2
Copying Arrow Files...
.copyArrow : Initializing Out ArrowFile
.copyArrow : Adding Metadata to Out ArrowFile
Error in .Call2("Rle_constructor", values, lengths, PACKAGE = "S4Vectors"): 'length(values)' != 'length(lengths)'
Traceback:
1. saveArchRProject(ArchRProj = projSpurp_doubletRemoved_filtered, 
 .     outputDirectory = "earlyCells_doubletRemoved_filtered2", 
 .     load = TRUE, dropCells = TRUE, threads = 1)
2. .copyArrows(inArrows = ArrowFiles, outArrows = ArrowFilesNew, 
 .     cellsKeep = ArchRProj$cellNames, logFile = logFile, threads = threads)
3. unlist(.safelapply(seq_along(inArrows), function(x) {
 .     .copyArrowSingle(inArrow = inArrows[x], outArrow = outArrows[x], 
 .         cellsKeep = cellsKeep, level = level, verbose = verbose, 
 .         logFile = logFile)
 . }, threads = threads))
4. .safelapply(seq_along(inArrows), function(x) {
 .     .copyArrowSingle(inArrow = inArrows[x], outArrow = outArrows[x], 
 .         cellsKeep = cellsKeep, level = level, verbose = verbose, 
 .         logFile = logFile)
 . }, threads = threads)
5. lapply(...)
6. FUN(X[[i]], ...)
7. .copyArrowSingle(inArrow = inArrows[x], outArrow = outArrows[x], 
 .     cellsKeep = cellsKeep, level = level, verbose = verbose, 
 .     logFile = logFile)
8. Rle(paste0(sampleName, "#", RGValues), RGLengths)
9. Rle(paste0(sampleName, "#", RGValues), RGLengths)
10. new_Rle(values, lengths)
11. .Call2("Rle_constructor", values, lengths, PACKAGE = "S4Vectors")

Any suggestions for debugging? It does seem that the arrow file is successfully copied, but something goes awry at the point of saving the metadata. 

My sessionInfo follows:

>R version 4.0.3 (2020-10-10)
Platform: x86_64-conda-linux-gnu (64-bit)
Running under: CentOS Linux 7 (Core)

Matrix products: default
BLAS/LAPACK: /fast/work/users/dgarfie_m/miniconda3/envs/ArchR/lib/libopenblasp-r0.3.12.so

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C              
 [3] LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8    
 [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8   
 [7] LC_PAPER=en_US.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C            
[11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] parallel  stats4    stats     graphics  grDevices utils     datasets 
[8] methods   base     

other attached packages:
 [1] plotly_4.9.3                dplyr_1.0.3                
 [3] ArchR_1.0.1                 magrittr_2.0.1             
 [5] rhdf5_2.34.0                Matrix_1.3-2               
 [7] data.table_1.13.6           SummarizedExperiment_1.20.0
 [9] Biobase_2.50.0              GenomicRanges_1.42.0       
[11] GenomeInfoDb_1.26.2         IRanges_2.24.1             
[13] S4Vectors_0.28.1            BiocGenerics_0.36.0        
[15] MatrixGenerics_1.2.0        matrixStats_0.57.0         
[17] ggplot2_3.3.3              

loaded via a namespace (and not attached):
 [1] pbdZMQ_0.3-4           tidyselect_1.1.0       repr_1.1.3            
 [4] purrr_0.3.4            lattice_0.20-41        colorspace_2.0-0      
 [7] vctrs_0.3.6            generics_0.1.0         viridisLite_0.3.0     
[10] htmltools_0.5.1.1      base64enc_0.1-3        rlang_0.4.10          
[13] pillar_1.4.7           glue_1.4.2             withr_2.4.1           
[16] DBI_1.1.1              uuid_0.1-4             GenomeInfoDbData_1.2.4
[19] lifecycle_0.2.0        stringr_1.4.0          zlibbioc_1.36.0       
[22] munsell_0.5.0          gtable_0.3.0           htmlwidgets_1.5.3     
[25] evaluate_0.14          IRdisplay_1.0          Rcpp_1.0.6            
[28] scales_1.1.1           IRkernel_1.1.1         DelayedArray_0.16.1   
[31] jsonlite_1.7.2         XVector_0.30.0         digest_0.6.27         
[34] stringi_1.5.3          grid_4.0.3             tools_4.0.3           
[37] bitops_1.0-6           rhdf5filters_1.2.0     lazyeval_0.2.2        
[40] RCurl_1.98-1.2         tibble_3.0.5           tidyr_1.1.2           
[43] crayon_1.3.4           pkgconfig_2.0.3        ellipsis_0.3.1        
[46] httr_1.4.2             assertthat_0.2.1       Rhdf5lib_1.12.0       
[49] R6_2.5.0               compiler_4.0.3

**Comment by jgranja24** [comment]
What happens if you use `dropCells = FALSE`?

**Comment by dagarfield** [comment]
It works totally fine in this case -- the saving works and I can reload the project without issues. 
However, I then get an error when using getMarkerFeatures, presumably related to https://github.com/GreenleafLab/ArchR/issues/483. I had assumed this is because all of the cells remain in the ArrowFiles, including ones that are no longer in the project itself.

**Comment by dagarfield** [comment]
Perhaps I should have been just using subsetArchRProject from the very start? Nonetheless, based on the tutorial, it did seem like directly subsetting a project was a viable route.

**Comment by dagarfield** [comment]
OK, I have a hunch what's going on here. Digging a bit into the errors and the Arrow files, I run quickly into this:

![image](https://user-images.githubusercontent.com/10536275/112936293-d21f0d80-9125-11eb-981f-d65f40c93850.png)

My guess is that the error y'all so kindly fixed earlier (creating arrow files if some chromosome has 0 reads) is showing up again here in the form of a chromosome/groupJ with no reads in it. This in turn causes an error at:
> RGRle <- Rle(paste0(sampleName, "#", RGValues), RGLengths)

While this error seems yet another argument in favour of your stance "mouse and human only", can you suggest a way around this issue (e.g. dropping from the project chromosomes with no reads in them)?

**Comment by dagarfield** [comment]
Current modified script is attached, if that helps.
[ArrowUtils.R.txt](https://github.com/GreenleafLab/ArchR/files/6234557/ArrowUtils.R.txt)

Saves fine now and removes chromosomes without any reads. Seems to fail for some chromosomes at the submatrix step, presumably because after filtering the corresponding submatrix entry (eg. genescore) is now 0.

**Comment by jgranja24** [comment]
Ill try to look more into this issue this week. These custom genomes confused me a bit with what to account for.

**Comment by dagarfield** [comment]
Great, thanks. For the moment, I've just got a little loop that subsets the input genes object for generating the gene score matrix to only contain chromosomes that aren't affected by this weird (presumably no coverage after filtering) issues, so I can move forward, but would good in the long-run not to fix. 

Let me know if example files etc. would be helpful in diagnostics and updates.

**Comment by jjoung** [comment]
Any updates on this issue? I am running into the sample problem. Thank you!

**Comment by rcorces** [comment]
No update yet.

**Comment by dagarfield** [comment]
And back at what appears to be this same error with the most recent ArchR (the error goes away when `dropCells = FALSE`).

I could re-implement the loop I did before that I did before, but it does seem like the error is a fairly straight-forward edge-case where some scaffolds/chromosomes and/or gene regions no longer have reads after filtering out cells. 

Was [this fix](https://github.com/GreenleafLab/ArchR/issues/671) implemented?

```
> proj<-saveArchRProject(ArchRProj = proj, outputDirectory = "filtered_proj1", load = TRUE, dropCells = TRUE)
Copying ArchRProject to new outputDirectory : /fast/work/projects/garfield-wrap-up/projects/13_alt_urchinATAC_processing/final_round_archR/archR_projects/filtered_proj1

Copying Arrow Files...

Warning message in mclapply(..., mc.cores = threads, mc.preschedule = preschedule):
“3 function calls resulted in an error”
Error in .safelapply(seq_along(inArrows), function(x) {: 
Error Found Iteration 1 : 
	[1] "Error in .Call2(\"Rle_constructor\", values, lengths, PACKAGE = \"S4Vectors\") : \n  'length(values)' != 'length(lengths)'\n"
	<simpleError in .Call2("Rle_constructor", values, lengths, PACKAGE = "S4Vectors"): 'length(values)' != 'length(lengths)'>
Error Found Iteration 2 : 
	[1] "Error in .Call2(\"Rle_constructor\", values, lengths, PACKAGE = \"S4Vectors\") : \n  'length(values)' != 'length(lengths)'\n"
	<simpleError in .Call2("Rle_constructor", values, lengths, PACKAGE = "S4Vectors"): 'length(values)' != 'length(lengths)'>
Error Found Iteration 3 : 
	[1] "Error in .Call2(\"Rle_constructor\", values, lengths, PACKAGE = \"S4Vectors\") : \n  'length(values)' != 'length(lengths)'\n"
	<simpleError in .Call2("Rle_constructor", values, lengths, PACKAGE = "S4Vectors"): 'length(values)' != 'length(lengths)'>

Traceback:

1. saveArchRProject(ArchRProj = proj, outputDirectory = "filtered_proj1", 
 .     load = TRUE, dropCells = TRUE)
2. .copyArrows(inArrows = ArrowFiles, outArrows = ArrowFilesNew, 
 .     cellsKeep = ArchRProj$cellNames, logFile = logFile, threads = threads)
3. unlist(.safelapply(seq_along(inArrows), function(x) {
 .     .copyArrowSingle(inArrow = inArrows[x], outArrow = outArrows[x], 
 .         cellsKeep = cellsKeep, level = level, verbose = verbose, 
 .         logFile = logFile)
 . }, threads = threads))
4. .safelapply(seq_along(inArrows), function(x) {
 .     .copyArrowSingle(inArrow = inArrows[x], outArrow = outArrows[x], 
 .         cellsKeep = cellsKeep, level = level, verbose = verbose, 
 .         logFile = logFile)
 . }, threads = threads)
5. stop(errorMsg)
```

**Comment by dagarfield** [comment]
(happy to provide test cases as always)

**Comment by rcorces** [comment]
I'm still on paternity leave but this issue was recently brought to my attention again. @dagarfield - would you be able to summarize the necessary changes again? I looked at the script you provided previously (https://github.com/GreenleafLab/ArchR/issues/663#issuecomment-810838830) and there are a lot of changes beyond the initial suggestions. 

I created a new branch called `dev_emptyChr` to hold and test these edits. I added what I interpreted to be the most important edit (the if statement testing length != 0) but I have a feeling that many of your other edits are important. I just cant tell which are for your own use case and which would be applicable to all ArchR users. (https://github.com/GreenleafLab/ArchR/blob/dev_emptyChr/R/ArrowUtils.R) 
commit - https://github.com/GreenleafLab/ArchR/commit/cff04476d37d5d34e65a5ba7a988b7ebffde08a1

Feel free to submit a pull request or let me know which changes are essential to try to wrap this up. Thanks as always for your help.

**Comment by rcorces** [comment]
@dagarfield - you reminded me of this issue. I'm trying to finalize a stable `release_1.0.2` soon and would love to wrap up some of these more important issues.

**Comment by jmmuncie** [comment]
Hi @rcorces - I ran into this problem described by @dagarfield. I'm also working with a custom genome and trying to subset a relatively small chunk of the dataset (3,300 of 21,000 cells) - so I'm assuming my issue is also due to one of my small "chromosomes" having zero reads in the group of cells I'm attempting to subset.

I installed the `dev_emptyChr` branch and was able to successfully create the subsetted ArchR project. I then had to reinstall `release_1.0.2` to avoid running into the `addIterativeLSI` error we addressed in #1325 and you fixed via #1333. 

However, I now encounter the errors below when attempting to `addIterativeLSI` for the `GeneExpressionMatrix` in the subsetted ArchR project. Since I didn't have an issue running `addIterativeLSI` for the `TileMatrix` I'm guessing this issue stems from the "empty" chromosomes being removed from the TileMatrix but not the RNA data when the project was subset? 

Hope this helps to get a stable fix for this into `release_1.0.2`

```
************************************************************
2022-04-06 15:11:35 : ERROR Found in .identifyVarFeatures for  
LogFile = ArchRLogs/ArchR-addIterativeLSI-18405bbd9fdf-Date-2022-04-06_Time-15-10-51.log

<simpleError in .safelapply(seq_along(seqnames), function(x) {    .logDiffTime(sprintf("Constructing Group Matrix %s of %s",         x, length(seqnames)), tstart, verbose = verbose)    seqnamex <- seqnames[x]    featureDFx <- featureDF[BiocGenerics::which(featureDF$seqnames %bcin%         seqnamex), ]    matChr <- matrix(0, nrow = nrow(featureDFx), ncol = length(groupList))    colnames(matChr) <- names(groupList)    rownames(matChr) <- rownames(featureDFx)    for (y in seq_along(ArrowFiles)) {        allCells <- allCellsList[[y]]        if (!is.null(allCells)) {            maty <- .getMatFromArrow(ArrowFile = ArrowFiles[y],                 useMatrix = useMatrix, featureDF = featureDFx,                 cellNames = allCells, useIndex = useIndex)            for (z in seq_along(groupList)) {                cellsGroupz <- groupList[[z]]                idx <- BiocGenerics::which(colnames(maty) %in%                   cellsGroupz)                if (length(idx) > 0) {                  matChr[, z] <- matChr[, z] + Matrix::rowSums(maty[,                     idx, drop = FALSE])                }            }            rm(maty)        }        if (y%%20 == 0 | y%%length(ArrowFiles) == 0) {            gc()        }    }    if (asSparse) {        matChr <- as(matChr, "dgCMatrix")    }    .logDiffTime(sprintf("Finished Group Matrix %s of %s", x,         length(seqnames)), tstart, verbose = verbose)    matChr}, threads = threads): 
Error Found Iteration 21 : 
	[1] "Error in h5read(ArrowFile, paste0(useMatrix, \"/\", seqnamex, \"/x\")) : \n  Object 'GeneExpressionMatrix/chrGL456210_chr1_random/x' does not exist in this HDF5 file.\n"
	<simpleError in h5read(ArrowFile, paste0(useMatrix, "/", seqnamex, "/x")): Object 'GeneExpressionMatrix/chrGL456210_chr1_random/x' does not exist in this HDF5 file.>
Error Found Iteration 22 : 
	[1] "Error in h5read(ArrowFile, paste0(useMatrix, \"/\", seqnamex, \"/x\")) : \n  Object 'GeneExpressionMatrix/chrGL456211_chr1_random/x' does not exist in this HDF5 file.\n"
	<simpleError in h5read(ArrowFile, paste0(useMatrix, "/", seqnamex, "/x")): Object 'GeneExpressionMatrix/chrGL456211_chr1_random/x' does not exist in this HDF5 file.>
Error Found Iteration 23 : 
	[1] "Error in h5read(ArrowFile, paste0(useMatrix, \"/\", seqnamex, \"/x\")) : \n  Object 'GeneExpressionMatrix/chrGL456212_chr1_random/x' does not exist in this HDF5 file.\n"
	<simpleError in h5read(ArrowFile, paste0(useMatrix, "/", seqnamex, "/x")): Object 'GeneExpressionMatrix/chrGL456212_chr1_random/x' does not exist in this HDF5 file.>
Error Found Iteration 25 : 
	[1] "Error in h5read(ArrowFile, paste0(useMatrix, \"/\", seqnamex, \"/x\")) : \n  Object 'GeneExpressionMatrix/chrGL456219_chr7_random/x' does not exist in this HDF5 file.\n"
	<simpleError in h5read(ArrowFile, paste0(useMatrix, "/", seqnamex, "/x")): Object 'GeneExpressionMatrix/chrGL456219_chr7_random/x' does not exist in this HDF5 file.>
Error Found Iteration 26 : 
	[1] "Error in h5read(ArrowFile, paste0(useMatrix, \"/\", seqnamex, \"/x\")) : \n  Object 'GeneExpressionMatrix/chrGL456221_chr1_random/x' does not exist in this HDF5 file.\n"
	<simpleError in h5read(ArrowFile, paste0(useMatrix, "/", seqnamex, "/x")): Object 'GeneExpressionMatrix/chrGL456221_chr1_random/x' does not exist in this HDF5 file.>
Error Found Iteration 28 : 
	[1] "Error in h5read(ArrowFile, paste0(useMatrix, \"/\", seqnamex, \"/x\")) : \n  Object 'GeneExpressionMatrix/chrGL456350_chr4_random/x' does not exist in this HDF5 file.\n"
	<simpleError in h5read(ArrowFile, paste0(useMatrix, "/", seqnamex, "/x")): Object 'GeneExpressionMatrix/chrGL456350_chr4_random/x' does not exist in this HDF5 file.>
Error Found Iteration 29 : 
	[1] "Error in h5read(ArrowFile, paste0(useMatrix, \"/\", seqnamex, \"/x\")) : \n  Object 'GeneExpressionMatrix/chrGL456354_chr5_random/x' does not exist in this HDF5 file.\n"
	<simpleError in h5read(ArrowFile, paste0(useMatrix, "/", seqnamex, "/x")): Object 'GeneExpressionMatrix/chrGL456354_chr5_random/x' does not exist in this HDF5 file.>
Error Found Iteration 30 : 
	[1] "Error in h5read(ArrowFile, paste0(useMatrix, \"/\", seqnamex, \"/x\")) : \n  Object 'GeneExpressionMatrix/chrJH584292_chr4_random/x' does not exist in this HDF5 file.\n"
	<simpleError in h5read(ArrowFile, paste0(useMatrix, "/", seqnamex, "/x")): Object 'GeneExpressionMatrix/chrJH584292_chr4_random/x' does not exist in this HDF5 file.>
Error Found Iteration 31 : 
	[1] "Error in h5read(ArrowFile, paste0(useMatrix, \"/\", seqnamex, \"/x\")) : \n  Object 'GeneExpressionMatrix/chrJH584293_chr4_random/x' does not exist in this HDF5 file.\n"
	<simpleError in h5read(ArrowFile, paste0(useMatrix, "/", seqnamex, "/x")): Object 'GeneExpressionMatrix/chrJH584293_chr4_random/x' does not exist in this HDF5 file.>
Error Found Iteration 32 : 
	[1] "Error in h5read(ArrowFile, paste0(useMatrix, \"/\", seqnamex, \"/x\")) : \n  Object 'GeneExpressionMatrix/chrJH584294_chr4_random/x' does not exist in this HDF5 file.\n"
	<simpleError in h5read(ArrowFile, paste0(useMatrix, "/", seqnamex, "/x")): Object 'GeneExpressionMatrix/chrJH584294_chr4_random/x' does not exist in this HDF5 file.>
Error Found Iteration 34 : 
	[1] "Error in h5read(ArrowFile, paste0(useMatrix, \"/\", seqnamex, \"/x\")) : \n  Object 'GeneExpressionMatrix/chrJH584296_chr5_random/x' does not exist in this HDF5 file.\n"
	<simpleError in h5read(ArrowFile, paste0(useMatrix, "/", seqnamex, "/x")): Object 'GeneExpressionMatrix/chrJH584296_chr5_random/x' does not exist in this HDF5 file.>
Error Found Iteration 35 : 
	[1] "Error in h5read(ArrowFile, paste0(useMatrix, \"/\", seqnamex, \"/x\")) : \n  Object 'GeneExpressionMatrix/chrJH584297_chr5_random/x' does not exist in this HDF5 file.\n"
	<simpleError in h5read(ArrowFile, paste0(useMatrix, "/", seqnamex, "/x")): Object 'GeneExpressionMatrix/chrJH584297_chr5_random/x' does not exist in this HDF5 file.>
Error Found Iteration 36 : 
	[1] "Error in h5read(ArrowFile, paste0(useMatrix, \"/\", seqnamex, \"/x\")) : \n  Object 'GeneExpressionMatrix/chrJH584298_chr5_random/x' does not exist in this HDF5 file.\n"
	<simpleError in h5read(ArrowFile, paste0(useMatrix, "/", seqnamex, "/x")): Object 'GeneExpressionMatrix/chrJH584298_chr5_random/x' does not exist in this HDF5 file.>
Error Found Iteration 37 : 
	[1] "Error in h5read(ArrowFile, paste0(useMatrix, \"/\", seqnamex, \"/x\")) : \n  Object 'GeneExpressionMatrix/chrJH584299_chr5_random/x' does not exist in this HDF5 file.\n"
	<simpleError in h5read(ArrowFile, paste0(useMatrix, "/", seqnamex, "/x")): Object 'GeneExpressionMatrix/chrJH584299_chr5_random/x' does not exist in this HDF5 file.>
>

************************************************************

Error in .logError(e, fn = ".identifyVarFeatures", info = "", errorList = errorList,  : 
  Exiting See Error Above
In addition: Warning message:
In mclapply(..., mc.cores = threads, mc.preschedule = preschedule) :
  14 function calls resulted in an error

**Comment by jmmuncie** [comment]
Hi @rcorces - I ran into this problem described by @dagarfield. I'm also working with a custom genome and trying to subset a relatively small chunk of the dataset (3,300 of 21,000 cells) - so I'm assuming my issue is also due to one of my small "chromosomes" having zero reads in the group of cells I'm attempting to subset.

I installed the `dev_emptyChr` branch and was able to successfully create the subsetted ArchR project. I then had to reinstall `release_1.0.2` to avoid running into the `addIterativeLSI` error we addressed in #1325 and you fixed via #1333. 

However, I now encounter the errors below when attempting to `addIterativeLSI` for the `GeneExpressionMatrix` in the subsetted ArchR project. Since I didn't have an issue running `addIterativeLSI` for the `TileMatrix` I'm guessing this issue stems from the "empty" chromosomes being removed from the TileMatrix but not the RNA data when the project was subset? 

Hope this helps to get a stable fix for this into `release_1.0.2`

```
************************************************************
2022-04-06 15:11:35 : ERROR Found in .identifyVarFeatures for  
LogFile = ArchRLogs/ArchR-addIterativeLSI-18405bbd9fdf-Date-2022-04-06_Time-15-10-51.log

<simpleError in .safelapply(seq_along(seqnames), function(x) {    .logDiffTime(sprintf("Constructing Group Matrix %s of %s",         x, length(seqnames)), tstart, verbose = verbose)    seqnamex <- seqnames[x]    featureDFx <- featureDF[BiocGenerics::which(featureDF$seqnames %bcin%         seqnamex), ]    matChr <- matrix(0, nrow = nrow(featureDFx), ncol = length(groupList))    colnames(matChr) <- names(groupList)    rownames(matChr) <- rownames(featureDFx)    for (y in seq_along(ArrowFiles)) {        allCells <- allCellsList[[y]]        if (!is.null(allCells)) {            maty <- .getMatFromArrow(ArrowFile = ArrowFiles[y],                 useMatrix = useMatrix, featureDF = featureDFx,                 cellNames = allCells, useIndex = useIndex)            for (z in seq_along(groupList)) {                cellsGroupz <- groupList[[z]]                idx <- BiocGenerics::which(colnames(maty) %in%                   cellsGroupz)                if (length(idx) > 0) {                  matChr[, z] <- matChr[, z] + Matrix::rowSums(maty[,                     idx, drop = FALSE])                }            }            rm(maty)        }        if (y%%20 == 0 | y%%length(ArrowFiles) == 0) {            gc()        }    }    if (asSparse) {        matChr <- as(matChr, "dgCMatrix")    }    .logDiffTime(sprintf("Finished Group Matrix %s of %s", x,         length(seqnames)), tstart, verbose = verbose)    matChr}, threads = threads): 
Error Found Iteration 21 : 
	[1] "Error in h5read(ArrowFile, paste0(useMatrix, \"/\", seqnamex, \"/x\")) : \n  Object 'GeneExpressionMatrix/chrGL456210_chr1_random/x' does not exist in this HDF5 file.\n"
	<simpleError in h5read(ArrowFile, paste0(useMatrix, "/", seqnamex, "/x")): Object 'GeneExpressionMatrix/chrGL456210_chr1_random/x' does not exist in this HDF5 file.>
Error Found Iteration 22 : 
	[1] "Error in h5read(ArrowFile, paste0(useMatrix, \"/\", seqnamex, \"/x\")) : \n  Object 'GeneExpressionMatrix/chrGL456211_chr1_random/x' does not exist in this HDF5 file.\n"
	<simpleError in h5read(ArrowFile, paste0(useMatrix, "/", seqnamex, "/x")): Object 'GeneExpressionMatrix/chrGL456211_chr1_random/x' does not exist in this HDF5 file.>
Error Found Iteration 23 : 
	[1] "Error in h5read(ArrowFile, paste0(useMatrix, \"/\", seqnamex, \"/x\")) : \n  Object 'GeneExpressionMatrix/chrGL456212_chr1_random/x' does not exist in this HDF5 file.\n"
	<simpleError in h5read(ArrowFile, paste0(useMatrix, "/", seqnamex, "/x")): Object 'GeneExpressionMatrix/chrGL456212_chr1_random/x' does not exist in this HDF5 file.>
Error Found Iteration 25 : 
	[1] "Error in h5read(ArrowFile, paste0(useMatrix, \"/\", seqnamex, \"/x\")) : \n  Object 'GeneExpressionMatrix/chrGL456219_chr7_random/x' does not exist in this HDF5 file.\n"
	<simpleError in h5read(ArrowFile, paste0(useMatrix, "/", seqnamex, "/x")): Object 'GeneExpressionMatrix/chrGL456219_chr7_random/x' does not exist in this HDF5 file.>
Error Found Iteration 26 : 
	[1] "Error in h5read(ArrowFile, paste0(useMatrix, \"/\", seqnamex, \"/x\")) : \n  Object 'GeneExpressionMatrix/chrGL456221_chr1_random/x' does not exist in this HDF5 file.\n"
	<simpleError in h5read(ArrowFile, paste0(useMatrix, "/", seqnamex, "/x")): Object 'GeneExpressionMatrix/chrGL456221_chr1_random/x' does not exist in this HDF5 file.>
Error Found Iteration 28 : 
	[1] "Error in h5read(ArrowFile, paste0(useMatrix, \"/\", seqnamex, \"/x\")) : \n  Object 'GeneExpressionMatrix/chrGL456350_chr4_random/x' does not exist in this HDF5 file.\n"
	<simpleError in h5read(ArrowFile, paste0(useMatrix, "/", seqnamex, "/x")): Object 'GeneExpressionMatrix/chrGL456350_chr4_random/x' does not exist in this HDF5 file.>
Error Found Iteration 29 : 
	[1] "Error in h5read(ArrowFile, paste0(useMatrix, \"/\", seqnamex, \"/x\")) : \n  Object 'GeneExpressionMatrix/chrGL456354_chr5_random/x' does not exist in this HDF5 file.\n"
	<simpleError in h5read(ArrowFile, paste0(useMatrix, "/", seqnamex, "/x")): Object 'GeneExpressionMatrix/chrGL456354_chr5_random/x' does not exist in this HDF5 file.>
Error Found Iteration 30 : 
	[1] "Error in h5read(ArrowFile, paste0(useMatrix, \"/\", seqnamex, \"/x\")) : \n  Object 'GeneExpressionMatrix/chrJH584292_chr4_random/x' does not exist in this HDF5 file.\n"
	<simpleError in h5read(ArrowFile, paste0(useMatrix, "/", seqnamex, "/x")): Object 'GeneExpressionMatrix/chrJH584292_chr4_random/x' does not exist in this HDF5 file.>
Error Found Iteration 31 : 
	[1] "Error in h5read(ArrowFile, paste0(useMatrix, \"/\", seqnamex, \"/x\")) : \n  Object 'GeneExpressionMatrix/chrJH584293_chr4_random/x' does not exist in this HDF5 file.\n"
	<simpleError in h5read(ArrowFile, paste0(useMatrix, "/", seqnamex, "/x")): Object 'GeneExpressionMatrix/chrJH584293_chr4_random/x' does not exist in this HDF5 file.>
Error Found Iteration 32 : 
	[1] "Error in h5read(ArrowFile, paste0(useMatrix, \"/\", seqnamex, \"/x\")) : \n  Object 'GeneExpressionMatrix/chrJH584294_chr4_random/x' does not exist in this HDF5 file.\n"
	<simpleError in h5read(ArrowFile, paste0(useMatrix, "/", seqnamex, "/x")): Object 'GeneExpressionMatrix/chrJH584294_chr4_random/x' does not exist in this HDF5 file.>
Error Found Iteration 34 : 
	[1] "Error in h5read(ArrowFile, paste0(useMatrix, \"/\", seqnamex, \"/x\")) : \n  Object 'GeneExpressionMatrix/chrJH584296_chr5_random/x' does not exist in this HDF5 file.\n"
	<simpleError in h5read(ArrowFile, paste0(useMatrix, "/", seqnamex, "/x")): Object 'GeneExpressionMatrix/chrJH584296_chr5_random/x' does not exist in this HDF5 file.>
Error Found Iteration 35 : 
	[1] "Error in h5read(ArrowFile, paste0(useMatrix, \"/\", seqnamex, \"/x\")) : \n  Object 'GeneExpressionMatrix/chrJH584297_chr5_random/x' does not exist in this HDF5 file.\n"
	<simpleError in h5read(ArrowFile, paste0(useMatrix, "/", seqnamex, "/x")): Object 'GeneExpressionMatrix/chrJH584297_chr5_random/x' does not exist in this HDF5 file.>
Error Found Iteration 36 : 
	[1] "Error in h5read(ArrowFile, paste0(useMatrix, \"/\", seqnamex, \"/x\")) : \n  Object 'GeneExpressionMatrix/chrJH584298_chr5_random/x' does not exist in this HDF5 file.\n"
	<simpleError in h5read(ArrowFile, paste0(useMatrix, "/", seqnamex, "/x")): Object 'GeneExpressionMatrix/chrJH584298_chr5_random/x' does not exist in this HDF5 file.>
Error Found Iteration 37 : 
	[1] "Error in h5read(ArrowFile, paste0(useMatrix, \"/\", seqnamex, \"/x\")) : \n  Object 'GeneExpressionMatrix/chrJH584299_chr5_random/x' does not exist in this HDF5 file.\n"
	<simpleError in h5read(ArrowFile, paste0(useMatrix, "/", seqnamex, "/x")): Object 'GeneExpressionMatrix/chrJH584299_chr5_random/x' does not exist in this HDF5 file.>
>

************************************************************

Error in .logError(e, fn = ".identifyVarFeatures", info = "", errorList = errorList,  : 
  Exiting See Error Above
In addition: Warning message:
In mclapply(..., mc.cores = threads, mc.preschedule = preschedule) :
  14 function calls resulted in an error
```
[ArchR-addIterativeLSI-18405bbd9fdf-Date-2022-04-06_Time-15-10-51.log](https://github.com/GreenleafLab/ArchR/files/8433282/ArchR-addIterativeLSI-18405bbd9fdf-Date-2022-04-06_Time-15-10-51.log)

**Comment by jmmuncie** [comment]
@rcorces Yeah it seems like it would be the other way around, but I made sure that these non-standard chromosomes are also contained in my `GeneExpressionMatrix`

```
> getSeqnames(proj_Mef2c_E775, useMatrix = "GeneExpressionMatrix")
 [1] "chr1"                    "chr10"                   "chr11"                   "chr12"                  
 [5] "chr13"                   "chr14"                   "chr15"                   "chr16"                  
 [9] "chr17"                   "chr18"                   "chr19"                   "chr2"                   
[13] "chr3"                    "chr4"                    "chr5"                    "chr6"                   
[17] "chr7"                    "chr8"                    "chr9"                    "chrF6-eGFP"             
[21] "chrGL456210_chr1_random" "chrGL456211_chr1_random" "chrGL456212_chr1_random" "chrGL456216_chr4_random"
[25] "chrGL456219_chr7_random" "chrGL456221_chr1_random" "chrGL456233_chrX_random" "chrGL456350_chr4_random"
[29] "chrGL456354_chr5_random" "chrJH584292_chr4_random" "chrJH584293_chr4_random" "chrJH584294_chr4_random"
[33] "chrJH584295_chr4_random" "chrJH584296_chr5_random" "chrJH584297_chr5_random" "chrJH584298_chr5_random"
[37] "chrJH584299_chr5_random" "chrJH584304_chrUn"       "chrX"    
```
I'll try to dig into this a little more later and see if I can figure out anything useful.

**Comment by rcorces** [comment]
@jmmuncie - can you check if the hdf5 groups (e.g. `GeneExpressionMatrix/chrJH584292_chr4_random/x`) actually exist in your arrows using `h5ls`?
https://rdrr.io/bioc/rhdf5/man/h5ls.html

**Comment by jmmuncie** [comment]
@rcorces - It looks like the groups do exist in all the arrow files, but their dimensions are `0 x 1` for many of them (I think all the ones that are throwing errors). Attaching an example of the `h5ls` result for one of my arrows.
[h5ls_sample.txt](https://github.com/GreenleafLab/ArchR/files/8445898/h5ls_sample.txt)

**Comment by rcorces** [comment]
@jmmuncie - an obvious solution would be to exclude these chromosomes from your analysis upfront. Either way, do you still think this is related to the issue at hand? if not, lets transfer discussion to a new issue

**Comment by jmmuncie** [comment]
@rcorces I made a mistake. I forgot that yesterday I had repeated the subsetting with `dropCells = FALSE`. After I set `dropCells = TRUE`, I can now see that the hdf5 groups (e.g. `GeneExpressionMatrix/chrJH584292_chr4_random/x`) do not exist for many of my pseudo-chromosomes.  

Below you can see the example for `chrJH584292_chr4_random` which does not contain a row for `chrJH584292_chr4_random/x` and throws and error, as well as for `chrJH584293_chr4_random` which does contain a row for `chrJH584293_chr4_random/x` and does not throw the error. 

```
418 /GeneExpressionMatrix chrJH584292_chr4_random   H5I_GROUP                     
419 /GeneExpressionMatrix/chrJH584292_chr4_random                 colSums H5I_DATASET    FLOAT    1048 x 1
420 /GeneExpressionMatrix/chrJH584292_chr4_random                       i H5I_DATASET  INTEGER       0 x 1
421 /GeneExpressionMatrix/chrJH584292_chr4_random                jLengths H5I_DATASET  INTEGER       0 x 1
422 /GeneExpressionMatrix/chrJH584292_chr4_random                 jValues H5I_DATASET  INTEGER       0 x 1
423 /GeneExpressionMatrix/chrJH584292_chr4_random            rowMeansLog2 H5I_DATASET    FLOAT       1 x 1
424 /GeneExpressionMatrix/chrJH584292_chr4_random                 rowSums H5I_DATASET    FLOAT       1 x 1
425 /GeneExpressionMatrix/chrJH584292_chr4_random             rowVarsLog2 H5I_DATASET    FLOAT       1 x 1
426                         /GeneExpressionMatrix chrJH584293_chr4_random   H5I_GROUP                     
427 /GeneExpressionMatrix/chrJH584293_chr4_random                 colSums H5I_DATASET    FLOAT    1048 x 1
428 /GeneExpressionMatrix/chrJH584293_chr4_random                       i H5I_DATASET  INTEGER       1 x 1
429 /GeneExpressionMatrix/chrJH584293_chr4_random                jLengths H5I_DATASET  INTEGER       1 x 1
430 /GeneExpressionMatrix/chrJH584293_chr4_random                 jValues H5I_DATASET  INTEGER       1 x 1
431 /GeneExpressionMatrix/chrJH584293_chr4_random            rowMeansLog2 H5I_DATASET    FLOAT       6 x 1
432 /GeneExpressionMatrix/chrJH584293_chr4_random                 rowSums H5I_DATASET    FLOAT       6 x 1
433 /GeneExpressionMatrix/chrJH584293_chr4_random             rowVarsLog2 H5I_DATASET    FLOAT       6 x 1
434 /GeneExpressionMatrix/chrJH584293_chr4_random                       x H5I_DATASET    FLOAT       1 x 1
```
If this doesn't suggest a straightforward solution, I can open up a new thread. Or if you think this is too much of a fringe case to work for a generalized solution, I'm comfortable just excluding these unlocalized chromosomes from my analysis now that I see how few (and in many cases zero) reads are mapped to them.

**Comment by rcorces** [comment]
so just to summarize, I think this is a downstream consequence of subsetting a project where the resulting project has no remaining information about a particular seqname.

can you try using the `excludeChr()` param to exclude the problematic chromosomes from `addIterativeLSI()`.

**Comment by jmmuncie** [comment]
@rcorces agree with your summary. Using the `excludeChr()` parameter in `addIterativeLSI()` does allow me to proceed and I've made it through dimensionality reduction, clustering, and plotting UMAPs with comparable results to subsetting with `dropCells = FALSE`.

So I'd say the fix you made in `dev_emptyChr` does work, and the only thing (if anything) that might be nice to add is a check/warning to list seqnames that will not have information in the resulting subset project so that those can be easily identified to use with `excludeChr()`

**Comment by rcorces** [comment]
@jmmuncie - I dont think the problem is the dimensions. 
For example, I can run:
```
> projHeme5_subset <- subsetArchRProject(ArchRProj = projHeme5, cells = cellNames, outputDirectory = "./projHeme5_subset", dropCells = TRUE)
```
And then check the arrow file and I see:
```
> library(rhdf5)
> h5ls(file = "./projHeme5_subset/ArrowFiles/scATAC_BMMC_R1.arrow")
                           group                  name       otype   dclass         dim
0                              /          ArchRVersion H5I_DATASET   STRING           1
1                              /                 Class H5I_DATASET   STRING           1
2                              /             Fragments   H5I_GROUP                     
3                     /Fragments                  chr1   H5I_GROUP                     
4                /Fragments/chr1             RGLengths H5I_DATASET  INTEGER        1606
5                /Fragments/chr1              RGValues H5I_DATASET   STRING        1606
6                /Fragments/chr1                Ranges H5I_DATASET  INTEGER  575295 x 2
7                     /Fragments                 chr10   H5I_GROUP                     
8               /Fragments/chr10             RGLengths H5I_DATASET  INTEGER        1606
9               /Fragments/chr10              RGValues H5I_DATASET   STRING        1606
10              /Fragments/chr10                Ranges H5I_DATASET  INTEGER  271845 x 2
```

whereas the original arrows show:
```
> h5ls(file = "./Save-ProjHeme5/ArrowFiles/scATAC_BMMC_R1.arrow")
                           group                  name       otype   dclass         dim
0                              /          ArchRVersion H5I_DATASET   STRING           1
1                              /                 Class H5I_DATASET   STRING           1
2                              /             Fragments   H5I_GROUP                     
3                     /Fragments                  chr1   H5I_GROUP                     
4                /Fragments/chr1             RGLengths H5I_DATASET  INTEGER    4932 x 1
5                /Fragments/chr1              RGValues H5I_DATASET   STRING    4932 x 1
6                /Fragments/chr1                Ranges H5I_DATASET  INTEGER 1509056 x 2
7                     /Fragments                 chr10   H5I_GROUP                     
8               /Fragments/chr10             RGLengths H5I_DATASET  INTEGER    4932 x 1
9               /Fragments/chr10              RGValues H5I_DATASET   STRING    4932 x 1
10              /Fragments/chr10                Ranges H5I_DATASET  INTEGER  715745 x 2
```

but `addGroupCoverages()` works just fine on the subset project, despite the dimensions of RGLengths and RGValues being different. 

Can you upload you logfile and try to figure out if this is failing on the first chromosome or something else?

**Comment by jmmuncie** [comment]
@rcorces You're right. Looking at the log helped me realize there are some chromosomes for which there are no `RGLengths` or `RGValues` and `addGroupCoverages()` is failing at the first instance of it (chrGL456350_chr4_random):
```
107                         /Fragments chrGL456233_chrX_random   H5I_GROUP                     
108 /Fragments/chrGL456233_chrX_random               RGLengths H5I_DATASET  INTEGER         498
109 /Fragments/chrGL456233_chrX_random                RGValues H5I_DATASET   STRING         498
110 /Fragments/chrGL456233_chrX_random                  Ranges H5I_DATASET  INTEGER     871 x 2
111                         /Fragments chrGL456350_chr4_random   H5I_GROUP                     
112                         /Fragments chrGL456354_chr5_random   H5I_GROUP                     
113 /Fragments/chrGL456354_chr5_random               RGLengths H5I_DATASET  INTEGER           5
114 /Fragments/chrGL456354_chr5_random                RGValues H5I_DATASET   STRING           5
115 /Fragments/chrGL456354_chr5_random                  Ranges H5I_DATASET  INTEGER       5 x 2
```
Whereas prior to subsetting with `dropCells = T` it's:
```
107                         /Fragments chrGL456233_chrX_random   H5I_GROUP                      
108 /Fragments/chrGL456233_chrX_random               RGLengths H5I_DATASET  INTEGER     3963 x 1
109 /Fragments/chrGL456233_chrX_random                RGValues H5I_DATASET   STRING     3963 x 1
110 /Fragments/chrGL456233_chrX_random                  Ranges H5I_DATASET  INTEGER     7398 x 2
111                         /Fragments chrGL456350_chr4_random   H5I_GROUP                      
112 /Fragments/chrGL456350_chr4_random               RGLengths H5I_DATASET  INTEGER        0 x 1
113 /Fragments/chrGL456350_chr4_random                RGValues H5I_DATASET   STRING            0
114 /Fragments/chrGL456350_chr4_random                  Ranges H5I_DATASET  INTEGER        0 x 2
115                         /Fragments chrGL456354_chr5_random   H5I_GROUP                      
116 /Fragments/chrGL456354_chr5_random               RGLengths H5I_DATASET  INTEGER       38 x 1
117 /Fragments/chrGL456354_chr5_random                RGValues H5I_DATASET   STRING       38 x 1
118 /Fragments/chrGL456354_chr5_random                  Ranges H5I_DATASET  INTEGER       38 x 2
```
[ArchR-addGroupCoverages-b5182ccb83ef-Date-2022-04-12_Time-21-51-13.log](https://github.com/GreenleafLab/ArchR/files/8478518/ArchR-addGroupCoverages-b5182ccb83ef-Date-2022-04-12_Time-21-51-13.log)

**Comment by rcorces** [comment]
@jmmuncie - I patched this by adding an `excludeChr` param to `addGroupCoverages()`. This was implemented in `dev_emptyChr` via 10f365ead6c575f2a2f38f90a4a9caecf76cdf6c

Could you see what happens when you try that and exclude the same chromosomes as you did for `addIterativeLSI()`? Eventually I want to try to autodetect which chromosomes will be a problem but at least this sets up removing them once detected.

**Comment by jmmuncie** [comment]
@rcorces yup, that works. Thank you!

**Comment by rcorces** [comment]
great. I'm sure there will be more problems downstream. Please continue to post as you hit them.

**Comment by jmmuncie** [comment]
Hi @rcorces - I have run into some downstream problems. I am attempting to use `addPeak2GeneLinks` and it is returning the same "Object does not exit in HDF5 file" errors. 

Also, I am anticipating that once I have my list of linked peaks and genes, I will want to add a column to the dataframe returned by `getPeak2GeneLinks` that includes the gene names. I believe the way to do this would be to match the indexes stored in the `idxRNA` column to the gene names by accessing the GeneExpressionMatrix via `getMatrixFromProject`. Does that sound right? If so, `getMatrixFromProject` also gives the "Object does not exist in HDF5" errors. 

Would it be possible to add the `excludeChr` parameter to both the `addPeak2GeneLinks` and `getMatrixFromProject` functions?

**Comment by rcorces** [comment]
@jmmuncie - for completeness, can you post log files and `traceback()` for both functions. I havent made a test project that I can use for this so I need help figuring out exactly where things are breaking.

**Comment by rcorces** [comment]
@jmmuncie

`excludeChr` should now work in `addPeak2GeneLinks()` after this commit https://github.com/GreenleafLab/ArchR/commit/10f365ead6c575f2a2f38f90a4a9caecf76cdf6c to `dev_emptyChr`

For `getMatrixFromProject()`, did you try passing the seqnames you want to `useSeqnames`? I know that is a not an optimal long-term solution for this workflow where we auto-remove empty chr, I'm just curious. I did also implement `excludeChr` in `getMatrixFromProject()` and `getMatrixFromArrow()` via https://github.com/GreenleafLab/ArchR/commit/41bea48d5c8d9e55f4cf8d5edac644a691ee4f95 to `dev_emptyChr`

Since I havent made a test project for this, please let me know if these work.

**Comment by jmmuncie** [comment]
@rcorces thanks for the fast turnaround and sorry for the delay on my end.

`getMatrixFromProject()` from the `dev_emptyChr` branch does now work with the `excludeChr` parameter. And with the `release_1.0.2` branch, passing the seqnames I want to `useSeqnames` also works, I just didn't notice it had that parameter. 

I'm still not able to run `addPeak2GeneLinks()`. I now get the following error in the console:
```
ArchR logging to : ArchRLogs/ArchR-addPeak2GeneLinks-fe202c251e46-Date-2022-04-30_Time-11-32-47.log
If there is an issue, please report to github with logFile!
2022-04-30 11:32:47 : Getting Available Matrices, 0.002 mins elapsed.
2022-04-30 11:32:47 : Filtered Low Prediction Score Cells (0 of 3368, 0), 0.003 mins elapsed.
2022-04-30 11:32:48 : Computing KNN, 0.008 mins elapsed.
2022-04-30 11:32:48 : Identifying Non-Overlapping KNN pairs, 0.009 mins elapsed.
2022-04-30 11:32:52 : Identified 453 Groupings!, 0.08 mins elapsed.
2022-04-30 11:32:52 : Getting Group RNA Matrix, 0.081 mins elapsed.
Error in mat[rownames(featureDF), , drop = FALSE] : 
  subscript out of bounds
```
With this `traceback()`:
```
2: .getGroupMatrix(ArrowFiles = getArrowFiles(ArchRProj), featureDF = geneDF, 
       groupList = knnObj, excludeSeqnames = excludeChr, useMatrix = useMatrix, 
       threads = threads, verbose = FALSE)
1: addPeak2GeneLinks(ArchRProj = proj_Mef2c_E775_subset_drop_CPsandCMs, 
       reducedDims = "LSI_Combined_sub_drop", useMatrix = "GeneExpressionMatrix", 
       excludeChr = c("chrGL456210_chr1_random", "chrGL456211_chr1_random", 
           "chrGL456212_chr1_random", "chrGL456219_chr7_random", 
           "chrGL456221_chr1_random", "chrGL456350_chr4_random", 
           "chrGL456354_chr5_random", "chrJH584292_chr4_random", 
           "chrJH584293_chr4_random", "chrJH584294_chr4_random", 
           "chrJH584296_chr5_random", "chrJH584297_chr5_random", 
           "chrJH584298_chr5_random", "chrJH584299_chr5_random"))
```
Log file attached. 
[ArchR-addPeak2GeneLinks-fe202c251e46-Date-2022-04-30_Time-11-32-47.log](https://github.com/GreenleafLab/ArchR/files/8597629/ArchR-addPeak2GeneLinks-fe202c251e46-Date-2022-04-30_Time-11-32-47.log)

**Comment by rcorces** [comment]
I've stared at this for a while and havent figured it out yet. Something is clearly off with how the matrix is being constructed but I cant figure out how the rownames wouldnt match.

It is failing here:
https://github.com/GreenleafLab/ArchR/blob/41bea48d5c8d9e55f4cf8d5edac644a691ee4f95/R/ArrowRead.R#L720

Maybe you can try to step through the code and figure it out?

**Comment by jmmuncie** [comment]
@rcorces okay, I'll give it a shot. Is there source code available for `addPeak2GeneLinks`? I'm having a hard time finding it. In particular, I'm trying to figure out how the `geneDF` dataframe is created and passed to `.getGroupMatrix`, since I don't provide it in the initial function call to `addPeak2GeneLinks`

**Comment by rcorces** [comment]
Here is `addPeak2GeneLinks()`
https://github.com/GreenleafLab/ArchR/blob/41bea48d5c8d9e55f4cf8d5edac644a691ee4f95/R/IntegrativeAnalysis.R#L977

**Comment by jmmuncie** [comment]
@rcorces okay thanks, I think I got to the bottom of it. The line you linked above is failing because the `featureDF` object contains more rows than the `mat` object. I'm pretty sure this is because `featureDF` contains all genes pulled from the GeneExpressionMatrix in the ArrowFiles, whereas the `mat` object only contains genes from the desired chromosomes (i.e. it takes into account the excluded chroms). 

`featureDF` originates by pulling the GeneInfo (lines 1067-1070): 
https://github.com/GreenleafLab/ArchR/blob/41bea48d5c8d9e55f4cf8d5edac644a691ee4f95/R/IntegrativeAnalysis.R#L1067
And then `geneDF` is created and passed to `.getGroupMatrix` as `featureDF` (lines 1104 and 1106):
https://github.com/GreenleafLab/ArchR/blob/41bea48d5c8d9e55f4cf8d5edac644a691ee4f95/R/IntegrativeAnalysis.R#L1103

Not exactly sure how to best implement a solution - probably to remove genes from excluded chroms from `geneDF` before it is passed to `.getGroupMatrix`?

**Comment by rcorces** [comment]
Thanks @jmmuncie. You're right. I ended up implementing this change both in `addPeak2GeneLinks()` and `.getGroupMatrix` for safety. It took me a few tries to get this right so the fixes are spread out across the following commits:
https://github.com/GreenleafLab/ArchR/commit/4277831b12443767ebb0081ec059fad1fffb541b
https://github.com/GreenleafLab/ArchR/commit/84b6748c83dc75cb40f91961e8544cc0edb783ae
https://github.com/GreenleafLab/ArchR/commit/b734a7b9dc297ed35e2d5f5f76139931e2e747e1

This should now be fixed in `dev_emptyChr`. Give it a try and let me know.

**Comment by jmmuncie** [comment]
@rcorces That works! Thanks so much for the help!

**Comment by rcorces** [comment]
@jmmuncie - If you have time, I've tried to introduce auto detection of problematic chromosomes in the following functions on a new branch called `dev_emptyChr2` via https://github.com/GreenleafLab/ArchR/commit/86fda3e27b474ad5c854dce6fcbfc80b5b3fc0bb:
`addIterativeLSI()`, `getMatrixFromProject()`, `addGroupCoverages()`, and `addPeak2GeneLinks()`.

I would really appreciate it if you could test this by running each function on your dataset without passing anything to `excludeChr` to make sure that it detects all of the problem chromosomes and then run again with `excludeChr` set to the suggested problem chromosomes. If this all looks good, I'll merge `dev_emptyChr2` into `dev_emptyChr`. The expected behavior is that the function should error out and tell you which chromosomes to pass to `excludeChr`.

**Comment by jmmuncie** [comment]
@rcorces thanks for taking the time to work on this! I'm happy to help test it out. I'll give it a try and report back soon.

**Comment by jmmuncie** [comment]
@rcorces Okay here's how it went.

`getMatrixFromProject()` error'd out but did not list the problem chromosomes, rather it spat out this:
```
Error in .safelapply(seq_along(ArrowFiles), function(x) { : 
Error Found Iteration 1 : 
	[1] "Error in paste(missing_chr_all, collapse = \",\") : \n  object 'missing_chr_all' not found\n"
	<simpleError in paste(missing_chr_all, collapse = ","): object 'missing_chr_all' not found>
Error Found Iteration 2 : 
	[1] "Error in paste(missing_chr_all, collapse = \",\") : \n  object 'missing_chr_all' not found\n"
	<simpleError in paste(missing_chr_all, collapse = ","): object 'missing_chr_all' not found>
Error Found Iteration 3 : 
	[1] "Error in paste(missing_chr_all, collapse = \",\") : \n  object 'missing_chr_all' not found\n"
	<simpleError in paste(missing_chr_all, collapse = ","): object 'missing_chr_all' not found>
Error Found Iteration 4 : 
	[1] "Error in paste(missing_chr_all, collapse = \",\") : \n  object 'missing_chr_all' not found\n"
	<simpleError in paste(missing_chr_all, collapse = ","): object 'missing_chr_all' not found>
In addition: Warning message:
In mclapply(..., mc.cores = threads, mc.preschedule = preschedule) :
  4 function calls resulted in an error
```
`additerativeLSI()` worked as expected for the ATAC data (when `useMatrix = "TileMatrix"`. However, it did not work as expected for GEX data (when `useMatrix = "GeneExpressionMatrix"`). It error'd out and provided a list of seqnames with no fragment information. However, in my dataset there are seqnames that do have fragment information but do not have gene expression information. So even after providing the auto-detected list of chromosomes to `excludeChr`, the function still fails.  Additionally, I encountered the `non-conformable arrays` error that we fixed in #1325 via d28fa1d61fd3a3444a01721785b6f32bce8cbf48 but is still a problem in this `dev_emptyChr2` branch. 

`addGroupCoverages()` error'd out and provided a list of seqnames with no fragment information. When I passed those to `excludeChr()`, the function failed again with the following error:
```
Error in .availableSeqnames(getArrowFiles(ArchRProj)) : 
  Not All Seqnames Identical!
```

`addPeak2GeneLinks()` error'd out and provided a list of seqnames with no fragment information. However, I then encountered the same problem as for `addIterativeLSI()` with GEX data - which is that there are additional seqnames with fragment information but no gene expression information. So even after passing the auto-detected chromosomes to `excludeChr`, the function failed when adding RNA Group Matrix with the following error:
```
2022-05-06 14:52:16 : Getting Group RNA Matrix, 0.087 mins elapsed.
Error in .safelapply(seq_along(seqnames), function(x) { : 
Error Found Iteration 21 : 
	[1] "Error in h5read(ArrowFile, paste0(useMatrix, \"/\", seqnamex, \"/x\")) : \n  Object 'GeneExpressionMatrix/chrGL456210_chr1_random/x' does not exist in this HDF5 file.\n"
	<simpleError in h5read(ArrowFile, paste0(useMatrix, "/", seqnamex, "/x")): Object 'GeneExpressionMatrix/chrGL456210_chr1_random/x' does not exist in this HDF5 file.>
Error Found Iteration 22 : 
	[1] "Error in h5read(ArrowFile, paste0(useMatrix, \"/\", seqnamex, \"/x\")) : \n  Object 'GeneExpressionMatrix/chrGL456211_chr1_random/x' does not exist in this HDF5 file.\n"
	<simpleError in h5read(ArrowFile, paste0(useMatrix, "/", seqnamex, "/x")): Object 'GeneExpressionMatrix/chrGL456211_chr1_random/x' does not exist in this HDF5 file.>
Error Found Iteration 23 : 
	[1] "Error in h5read(ArrowFile, paste0(useMatrix, \"/\", seqnamex, \"/x\")) : \n  Object 'GeneExpressionMatrix/chrGL456212_chr1_random/x' does not exist in this HDF5 file.\n"
	<simpleError in h5read(ArrowFile, paste0(u
In addition: Warning message:
In mclapply(..., mc.cores = threads, mc.preschedule = preschedule) :
  10 function calls resulted in an error
```

I'm happy to help continue testing updates but also want to let you know that for my own datasets, I am now convinced that these unlocalized non-standard chromosomes aren't significant to my analyses and I'll just be excluding them from the get-go.

**Comment by rcorces** [comment]
I *think* this has all been handled appropriately though automated detection still isnt enabled. But the relevant changes listed throughout the posts above have been incorporated into the `dev` branch and will be part of `release_1.0.3`. Closing for now.
